# Day 05 Daily Log

## Topic

Testbench practice and verification-oriented simulation

## What I Learned

* I learned that a testbench is not hardware.
* I learned that a testbench is a verification environment used to drive inputs, check outputs, and generate waveforms.
* I learned how to use expected values to automatically check whether a module output is correct.
* I learned how to print PASS or FAIL results in the terminal using `$display`.
* I learned how to use `task` to reduce repeated testbench code.
* I learned that task input parameters are matched by position, not by name.
* I learned that task input values must be assigned to the real testbench signals connected to the DUT.
* I reviewed how `$dumpfile`, `$dumpvars`, `$finish`, and `#10` are used in simulation.
* I debugged common Verilog testbench issues, including missing backticks, wrong task parameter names, incorrect file paths, and mismatched signal widths.

## What I Built / Produced

* Refined ALU testbench: `04_testbench_practice/tb_refine/alu_tb_refine.v`
* Refined MUX testbench: `04_testbench_practice/tb_refine/mux2to1_tb_refine.v`
* Refined decoder testbench: `04_testbench_practice/tb_refine/decoder2to4_tb_refine.v`
* Refined full adder testbench: `04_testbench_practice/tb_refine/full_adder_tb_refine.v`
* Simulation outputs: `04_testbench_practice/sim/`
* Waveform files: `04_testbench_practice/waves/`
* Testbench notes: `04_testbench_practice/notes/testbench-notes.md`
* README: `04_testbench_practice/README.md`

## Key Concepts

### Testbench

A testbench is a simulation environment.

It is used to verify whether a Verilog module behaves correctly.

### DUT

DUT means Device Under Test.

It is the hardware module being tested by the testbench.

### Stimulus

Stimulus means the input values applied to the DUT.

The testbench drives stimulus into the module and observes the output.

### Expected Result

Expected result means the correct output that the testbench uses as a reference.

It is written by the testbench writer.

### Actual Result

Actual result means the output generated by the DUT.

The testbench compares the actual result with the expected result.

### PASS / FAIL

PASS means the actual output matches the expected output.

FAIL means at least one actual output does not match the expected output.

### Task

A task is used to group repeated testbench actions.

It helps make the testbench cleaner and easier to extend.

### `$display`

`$display` prints simulation information in the terminal.

It is useful for showing input values, actual outputs, expected outputs, and PASS / FAIL results.

### `$dumpfile`

`$dumpfile` specifies the VCD waveform file path.

The path must be written inside double quotes.

### `$dumpvars`

`$dumpvars` records signals into the VCD waveform file.

### `$finish`

`$finish` ends the simulation.

### `#10`

`#10` waits for 10 simulation time units.

In this project, it gives the DUT time to update before the testbench checks the output.

## Problems and Fixes

### Problem

The VCD file path caused an error.

### Fix

I fixed the path by matching the `$dumpfile` path with the terminal working directory.

### Problem

The first line of one testbench caused a syntax error.

### Fix

The `timescale` directive was missing the backtick. I fixed it by writing:

```verilog
`timescale 1ns/1ps
```

### Problem

A task input name did not match the name used inside the task.

### Fix

I made the task parameter name and assignment name consistent.

For example, `test_opcode` must be used consistently if the task input is declared as `test_opcode`.

### Problem

One signal output was displayed incorrectly because the testbench signal width did not match the DUT output width.

### Fix

I made the testbench signal width match the DUT output width.

For example, a 4-bit DUT output should be connected to a 4-bit testbench wire.

### Problem

I was confused about why `a = test_a` is necessary inside a task.

### Fix

I learned that `test_a` is only a task input parameter. It is not automatically connected to the DUT. The assignment `a = test_a` sends the task input value to the real testbench signal connected to the DUT.

## Connection to VLSI / EDA / 3D IC

Verification is a core part of digital IC design.

Writing RTL is not enough. A designer must also prove that the RTL behaves correctly under different input conditions.

In real VLSI and EDA workflows, functional verification happens before synthesis, physical design, routing, and timing analysis. A good testbench helps catch design bugs early, before they become more expensive to fix later in the chip design flow.

This practice builds the foundation for more advanced verification methods used in ASIC design, EDA tools, and larger RTL systems.

## One Sentence Summary

Today I learned how to improve Verilog testbenches by adding expected results, automatic PASS / FAIL checks, reusable tasks, and waveform-based debugging.

## Next Step

* Move into sequential logic practice.
* Learn how clock, reset, and registers change the way testbenches are written.
* Prepare for counter-related Verilog modules.
